#!/bin/bash
# destroys all class files and temp files

rm -f *.class
rm -f */*.class
rm -f */*/*.class

rm -f *~
rm -f */*~
rm -f */*/*~

# If it's Karla's computer, don't clear the screen
if [ `whoami` == "damon" ]; thenfi
   reset

