#!/bin/bash
# Benjamin James Wright (bwright@cse.unsw.edu.au)
# 2012.04.07 (ISO 8601)
# Generates the javadoc documentation for the framework to a folder in /tmp/
# then moves those files into the gh-pages branch inside the doc/ file.
# It then commits these changes but does not push them.

# Define the project root
PROJECT_ROOT="`dirname $(pwd)`"
# The location of the package.
PACKAGE_PATH="$PROJECT_ROOT/src/"
# The name of the package.
PACKAGE_NAME=framework
# Get the javadoc version.
JAVADOC_VERSION="`javadoc -J-fullversion | head -1`"
# Create a temporary directory to place the new documentation in.
javadoc_tmp=`mktemp -d`
# Generate the documentation  to the temp directory.
echo "[Documentation] - Generating Javadoc to $javadoc_tmp"
pushd "$PACKAGE_PATH"
javadoc $PACKAGE_NAME -d $javadoc_tmp
popd
# Move the generated java documentation to the gh-pages branch.
echo "[Documentation] - Moving the documentation to the gh-pages branch"
# Move to the root of the project
pushd "$PROJECT_ROOT"
# Checkout github pages.
git checkout gh-pages
# Move the java documentation from the tmp file to the project documentaiton.
mv "$javadoc_tmp/"* "doc/"
# Commit the updated documentation.
echo "[Documentation] - Commiting the new documentation to gh-pages branch"
# Add the files to the documentation.
git add "$PROJECT_ROOT/doc"
# Commit the project within the current gh-pages branch.
git commit -a -m "Javadoc autogenerated with version $JAVADOC_VERSION at `date "+%F-%X"`"
# Checkout the previously opened branch
git checkout -
popd
