#!/bin/bash
# requires java, javac.
# Copyright (C) 2012    Lasath Fernando         (@lasath.fernando)
# Copyright (C) 2012    Benjamin James Wright   (@ben.wright)
# Copyright (C) 2012    Damon Stacey            (@damon.stacey)

export BASE_DIR="`cd .. ; pwd`"
export SRC_DIR="$BASE_DIR/src"
export BUILD_DIR="$BASE_DIR/build"

# Don't continue after errors
set -e

echo Compiling...
mkdir -p $BUILD_DIR

pushd $SRC_DIR
# this will automatically compile any imported files whose source
# has modified since last compile.
javac -source 1.6 -d $BUILD_DIR -sourcepath . framework/TestRunner.java
popd

echo Compilation Complete!

